image:
  repository: "luizvinicius/bank-api"
  tag: "1.0.2"

replicas: "1"

service:
  port: "8080"

env:
  DB_USER: appuser
  DB_URL: jdbc:postgresql://devops-back-rw.default:5432/appdb
  DB_DDL_AUTO: update

applicationSecret:
  password: app@123