image:
  repository: "luizvinicius/bank-api"
  tag: "1.0.3"

replicas: "3"

service:
  port: "8080"

rollout:
  enabled: true
strategy: "bluegreen"

job:
  enabled: false

env:
  DB_USER: appuser
  DB_URL: jdbc:postgresql://devops-back-rw.default:5432/appdb
  DB_DDL_AUTO: update

applicationSecret:
  password: app@123